services:
  app:
    build: .
    container_name: php_rest_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: lab
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: php_rest_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: php_rest_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
